export const customers = [
    { id: 1, name: 'Ethan C Welsh', mrr: '$120', arr: '$1,440', plan: 'Elite', billing: 'Monthly', payment: '$120', country: 'United States', since: 'Oct 14, 2025', status: 'Active' },
    { id: 2, name: 'MD SHAHID B EMDAD', mrr: '$24', arr: '$288', plan: 'Elite', billing: 'Monthly', payment: '$24', country: 'United States', since: 'Oct 13, 2025', status: 'Active' },
    { id: 3, name: 'Evan Nebab', mrr: '$0.60', arr: '$7.20', plan: 'Advanced', billing: 'Monthly', payment: '$0.60', country: 'United States', since: 'Sep 30, 2025', status: 'Active' },
    { id: 4, name: 'Luis Delpino', mrr: '$12', arr: '$144', plan: 'Elite', billing: 'Monthly', payment: '$12', country: 'United States', since: 'Sep 21, 2025', status: 'Active', note: 'Cancelling in 5 days' },
    { id: 5, name: 'Thien Nguyen', mrr: '$0.60', arr: '$7.20', plan: 'Advanced', billing: 'Monthly', payment: '$0.60', country: 'United States', since: 'Sep 17, 2025', status: 'Active' },
    { id: 6, name: 'Vincent Nicchia', mrr: '$6', arr: '$72', plan: 'Advanced', billing: 'Monthly', payment: '$6', country: 'United States', since: 'Sep 17, 2025', status: 'Active' },
    { id: 7, name: 'Brock Stewart', mrr: '$12', arr: '$144', plan: 'Elite', billing: 'Monthly', payment: '$12', country: 'United States', since: 'Sep 16, 2025', status: 'Active' },
    { id: 8, name: 'Jacob malamud', mrr: '$12', arr: '$144', plan: 'Elite', billing: 'Monthly', payment: '$12', country: 'United States', since: 'Sep 16, 2025', status: 'Active' },
    { id: 9, name: 'Jacob Malamud', mrr: '$12', arr: '$144', plan: 'Elite', billing: 'Monthly', payment: '$12', country: 'United States', since: 'Sep 16, 2025', status: 'Active' },
    { id: 10, name: 'Advaith Malka', mrr: '$120', arr: '$1,440', plan: 'Elite', billing: 'Monthly', payment: '$132', country: 'United States', since: 'Sep 12, 2025', status: 'Active' },
    { id: 11, name: 'rishi.singh0619@gmail.com', mrr: '$120', arr: '$1,440', plan: 'Elite', billing: 'Monthly', payment: '$132', country: 'United States', since: 'Sep 11, 2025', status: 'Active' },
    { id: 12, name: 'Patrick Merriman', mrr: '$120', arr: '$1,440', plan: 'Elite', billing: 'Monthly', payment: '$132', country: 'United States', since: 'Sep 5, 2025', status: 'Active' },
    { id: 13, name: "Trenton O'Neill", mrr: '$120', arr: '$1,440', plan: 'Elite', billing: 'Monthly', payment: '$240', country: 'United States', since: 'Sep 4, 2025', status: 'Active' },
    { id: 14, name: 'Eva Shindin', mrr: '$60', arr: '$720', plan: 'Advanced', billing: 'Monthly', payment: '$120', country: 'United States', since: 'Sep 3, 2025', status: 'Active' },
];